# Generated by Django 5.0.4 on 2024-04-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librerias', '0002_libro_cantidad_libro_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Especificaciones',
            field=models.TextField(null=True, verbose_name='Especificaciones'),
        ),
    ]
